import uuid
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from db import init_db, insert_log, get_logs, update_log_appeal, verify_creator, is_creator_verified, get_analytics
from signals import evaluate_with_groq, evaluate_stylometrics

app = Flask(__name__)

# Initialize Rate Limiter
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# Initialize the database
init_db()

def get_label_for_score(score):
    if score >= 0.65:
        return "This content was likely generated by AI."
    elif score <= 0.35:
        return "This content was likely written by a human."
    else:
        return "The origin of this content is unclear; it may contain a mix of human and AI generation."

def get_attribution_for_score(score):
    if score >= 0.65:
        return "likely_ai"
    elif score <= 0.35:
        return "likely_human"
    else:
        return "uncertain"

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    
    if not data or 'text' not in data or 'creator_id' not in data:
        return jsonify({"error": "Missing 'text' or 'creator_id'"}), 400
        
    text = data['text']
    creator_id = data['creator_id']
    metadata = data.get('metadata', None)
    
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()
    
    # 1. Run First Signal
    llm_score = evaluate_with_groq(text, metadata)
    
    # 2. Run Second Signal (Stylometrics)
    stylometric_score = evaluate_stylometrics(text)
    
    # 3. Confidence Score (Average of both signals)
    confidence = (llm_score + stylometric_score) / 2.0
    
    # 4. Label & Attribution
    attribution = get_attribution_for_score(confidence)
    label = get_label_for_score(confidence)
    
    # Check if the creator is verified (Provenance Certificate)
    is_verified = is_creator_verified(creator_id)
    if is_verified:
        label += " 🏅 Verified Human"
    
    # 5. Audit Log
    has_metadata = 1 if metadata else 0
    insert_log(
        content_id=content_id,
        creator_id=creator_id,
        timestamp=timestamp,
        attribution=attribution,
        confidence=confidence,
        llm_score=llm_score,
        stylometric_score=stylometric_score,
        status="classified",
        has_metadata=has_metadata
    )
    
    response_data = {
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label
    }
    if is_verified:
        response_data["verified_human"] = True
        
    return jsonify(response_data)

@app.route("/log", methods=["GET"])
def view_log():
    logs = get_logs()
    return jsonify({"entries": logs})

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or 'content_id' not in data or 'creator_reasoning' not in data:
        return jsonify({"error": "Missing 'content_id' or 'creator_reasoning'"}), 400
        
    update_log_appeal(data['content_id'], data['creator_reasoning'])
    
    return jsonify({"message": "Appeal received and status updated to 'under_review'."})

@app.route("/verify", methods=["POST"])
def verify():
    data = request.get_json()
    if not data or 'creator_id' not in data:
        return jsonify({"error": "Missing 'creator_id'"}), 400
        
    timestamp = datetime.now(timezone.utc).isoformat()
    verify_creator(data['creator_id'], timestamp)
    
    return jsonify({"message": f"Creator {data['creator_id']} has been successfully verified."})

@app.route("/analytics", methods=["GET"])
def analytics():
    data = get_analytics()
    return jsonify(data)

if __name__ == "__main__":
    app.run(debug=True, port=5001)
