import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# Initialize Groq client
client = Groq(
    api_key=os.environ.get("GROQ_API_KEY"),
)

def evaluate_with_groq(text, metadata=None):
    """
    Evaluates the given text using Groq's LLM to determine if it is human or AI generated.
    Returns a score between 0.0 (Definitely Human) and 1.0 (Definitely AI).
    """
    try:
        # Create a combined prompt if metadata is present
        metadata_str = ""
        if metadata:
            metadata_str = f"\n\nHere is some structured metadata associated with this content: {metadata}. Consider if this metadata looks synthetic or mismatched."
            
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": "You are a text classification system. Determine if the following text was generated by an AI or written by a human. Respond ONLY with a JSON object containing a single key 'ai_likelihood' with a float value between 0.0 (certainly human) and 1.0 (certainly AI)."
                },
                {
                    "role": "user",
                    "content": text + metadata_str
                }
            ],
            response_format={"type": "json_object"}
        )
        
        result_json = response.choices[0].message.content
        import json
        result = json.loads(result_json)
        
        score = result.get("ai_likelihood", 0.5)
        # Ensure score is within bounds
        return max(0.0, min(1.0, float(score)))
        
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        # Default to maximum uncertainty if the API call fails
        return 0.5

def evaluate_stylometrics(text):
    """
    Evaluates the given text using stylometric heuristics.
    Calculates Type-Token Ratio (vocabulary diversity) and Sentence Length Variance.
    Returns a score between 0.0 (Human) and 1.0 (AI).
    """
    import re
    
    words = re.findall(r'\b\w+\b', text.lower())
    if not words:
        return 0.5
        
    # Vocabulary diversity (Type-Token Ratio)
    unique_words = set(words)
    ttr = len(unique_words) / len(words)
    
    # AI writing often has a moderate TTR because it avoids extreme repetition but also avoids highly obscure vocabulary.
    # Human writing varies wildly. We'll use this as a minor signal.
    
    # Sentence length variation
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    if not sentences:
        return 0.5
        
    sentence_lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    avg_length = sum(sentence_lengths) / len(sentences)
    
    # Calculate variance
    if len(sentences) > 1:
        variance = sum((l - avg_length) ** 2 for l in sentence_lengths) / (len(sentences) - 1)
    else:
        variance = 0
        
    # Heuristic scoring logic:
    # High variance in sentence length -> Likely Human (closer to 0.0)
    # Low variance in sentence length -> Likely AI (closer to 1.0)
    # This is a very simplified heuristic for demonstration purposes.
    
    if variance < 10:
        score = 0.8
    elif variance < 20:
        score = 0.6
    elif variance < 40:
        score = 0.4
    else:
        score = 0.2
        
    # Extremely short texts default to uncertainty
    if len(words) < 15:
        score = 0.5
        
    return score
